<%@ page pageEncoding="UTF-8"%>
    <h1 style="text-align: center">爱心宠物诊所系统</h1>
    <div class="container">
        <header class="d-flex justify-content-center py-3">
            <ul class="nav nav-pills">
                <li class="nav-item"><a href="vetsearch.jsp" class="nav-link active" aria-current="request">兽医管理</a></li>
                <li class="nav-item"><a href="customersearch.jsp" class="nav-link active" active" aria-current="request">客户管理</a></li>
                <li class="nav-item"><a href="petSearch.jsp" class="nav-link active" active" aria-current="request">宠物管理</a></li>
                <li class="nav-item"><a href="treatSearch.jsp" class="nav-link active" active" aria-current="request">就诊管理</a></li>
                <li class="nav-item"><a href="QuitServlet" class="nav-link activate" active" aria-current="request">退出</a></li>
            </ul>
        </header>
    </div>